version: '3'
services:
  bitsand:
    build:
      context: .
      dockerfile: Dockerfile.ecs
    ports:
      - "80:80"
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - BITSAND_SYSTEM_NAME=local
      - BITSAND_INSTALL_MODE=TRUE
      - BITSAND_ROOT_USER_ID=1
      - BITSAND_DB_TYPE=mysql
      - BITSAND_DB_HOST=mysql
      - BITSAND_DB_NAME=bitsandtest
      - BITSAND_DB_USER=bitsandtest
      - SSM_AWS_REGION=${AWS_REGION}
      - SSM_KEY_BITSAND_DB_PASS=/bitsand-dev/local/db_pass
      - SSM_KEY_BITSAND_ENCRYPTION_KEY=/bitsand-dev/local/encryption_key
      - SSM_KEY_BITSAND_PW_SALT=/bitsand-dev/local/pw_salt
      - BITSAND_SYSTEM_URL=http://127.0.0.1/
      - BITSAND_DEBUG_MODE=FALSE
      - BITSAND_MAINTAINENCE_MODE=FALSE
      - BITSAND_LOG_WARNINGS=TRUE
      - BITSAND_LOG_ERRORS=TRUE
    depends_on:
      - mailhog
      - mysql

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=ev3aem6quaLaem0aeba4osheeloh1aeV2quei6Ea1soleed9XeeGh5ohmooxohtim7vaigeiquai5aich5xikiothee9hee0oi9i
      - MYSQL_DATABASE=bitsandtest
      - MYSQL_USER=bitsandtest
      - MYSQL_PASSWORD=Lahja3lie5wohphahna7IhailiemupohL3Aehoa2Oil9ahD7iMohvei1tuuG3akusoohooleecai9moogah1eiNooSh9yoo2thai
    volumes:
      - mysql:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  mysql:
    driver: local
